server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/footcatalogdb}
    username: ${POSTGRES_DATABASE_USER:postgres}
    password: ${POSTGRES_DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  application:
    name: FOOD_CATALOG_SERVICE

